version: "3.7"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - maria_db
#      - nginx
    command: sh -c './wait-for mysql_db:3306 -- npm start'
#  nginx:
#    container_name: nginx-server
#    build: ./nginx
##    image: nginx
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    labels:
#      - sh.acme.autoload.domain=tsaheylu.me
#    volumes:
#      - ./staticHTML:/usr/share/nginx/static
#      - ./nginx/conf.d:/etc/nginx/conf.d
#       - ./home/ssl/:/home/ssl/
#    depends_on:
#      - api_service
  maria_db:
    build: ./mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d/
      - ./mariadb/sql:/opt/sql
    container_name: 'mariadb-server'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
